### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by lykius** [lzhengning/SubdivNet#29]
I'm trying to use your script `datagen_maps.py` to preprocess some meshes in order to feed them to SubDivNet.
The meshes are obtained with marching cubes and I tried different resolutions to get meshes with different number of vertices/faces.
The preprocessing fails in the `decimate()` function [here](https://github.com/lzhengning/SubdivNet/blob/db875aac9117a7bdd86868746088b5efcbc745f5/maps/maps.py#L364), without any meaningful error (at least that I can understand).

Do you have any suggestion? Is there any special requirement for the meshes in order to be able to preprocess them?

Thanks in advance!

**Comment by lzhengning** [comment]
Sorry that I forgot to further reply to your question.

I have try the remeshing script to a few of your provided meshes. The algorithm seems Okay in my cases. 

before remeshing:
<img width="409" alt="截屏2022-05-19 16 23 52" src="https://user-images.githubusercontent.com/6365477/169248018-8aa1d344-53fe-4e0b-b54c-49f942ce741e.png">

after remeshing:
<img width="409" alt="截屏2022-05-19 16 23 47" src="https://user-images.githubusercontent.com/6365477/169248033-55834185-22ce-4511-bc8e-df5bffb62555.png">

However, the scripts is really slow to process the 64^3 meshes. There is a `timeout` configuration in the `make_MAPS_dataset` function. Enlarging `timeout` will stop the scripts from early exiting. However, I would suggest to simplify the inputs before remeshing rather than consuming more time.
