### ISSUE TITLE
question concerning labeling the data

### ISSUE THREAD

**Issue by hamzam0n** [lzhengning/SubdivNet#30]
Hello, thanks for your great work and offered code.

i'm working on a school project and i  want to use the SUBDIVNET code to train my data, but there are some points i did not understand..

in each .obj file there are 3 indexes: 

- **raw_labels**: each item here represents a label of a face in the original data.
- **sub_labels**:  each item here represents a label of a face in the data after remeshing it   `(after applying datagen_maps.py on it ) `
- **raw_to_sub**: _**this i don't understand what does it represent, and what is its role**_

another thing i didn't understand: length of  raw_labels and sub_labels is **13776** but number of faces in each object is  **16384**.
so if    raw_labels and sub_labels are representing the label of each face why they don't have same length as faces.

so can you please explain to me how can i preprocess step by step my data to before feeding it  to the subdivnet?
how can i make each object have the exact number of faces as in your input data (16384)
and how to label my data, and if you can recommend me a tool i can use!

thank you in advance

**Comment by lzhengning** [comment]
Sorry for the late response.

https://github.com/lzhengning/SubdivNet/issues/9#issuecomment-885535277 may answer the first question.

The later problem should not occur. Because the length of raw_labels should be the same with the number of faces in the **raw mesh**, and length of **sub_labels** should be that of the remeshed shape, which is the direct input of SubdivNet. In your case, there ought to be 16384 **sub_labels**. 

Please have another look at the json file. You can further provide me the file if I am wrong.

If you want to remesh your own data, please see the corresponding section in README. The paper also provides a detailed discussion about the remeshing algorithm. To precess shapes to 16384 (= 256 * 4^3) faces, the base mesh should be 256, and the subdivision depth is 3.

**Comment by hamzam0n** [comment]
thank you for making things clear
things are clear now, that's close the issue
